kind: pipeline
type: docker
name: script-firefly-iii-budget-resp-lb

steps:
  - name: Build clear
    image: golang:alpine3.19
    commands:
      - apk add make zip
      - make build
    when:
      branch:
      - master

  - name: Deploy to lambda
    image: alpine/k8s:1.26.13
    commands:
      - aws lambda update-function-code \
        --function-name $LAMBDA_NAME \
        --zip-file ./main.zip
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      LAMBDA_NAME: "firefly-iii-budget-resp"
      AWS_REGION: 'us-east-1'
    when:
      branch:
      - master

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
